name: deploy to github pages

on: 
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: setup node
      uses: actions/setup-node@master
      with:
        node-version: '12.x'

    - name: yarn install 
      run: yarn install

    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
