name: deploy to github pages

on: 
  push:
    branches:
      - master
      - mizdra-patch-1

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: setup node
      uses: actions/setup-node@master
      with:
        node-version: '12.x'

    - name: yarn install 
      run: yarn install

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
